# Generated by Django 5.2.4 on 2025-07-10 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersection',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.package'),
        ),
        migrations.AddField(
            model_name='footerimage',
            name='footer_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='admin_panel.footersection'),
        ),
        migrations.AddField(
            model_name='limiteddealimage',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='admin_panel.limiteddeal'),
        ),
        migrations.AddField(
            model_name='otpsession',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_otp_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seasontime',
            name='sight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='admin_panel.sight'),
        ),
        migrations.AddField(
            model_name='experience',
            name='sight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='admin_panel.sight'),
        ),
        migrations.AddField(
            model_name='sightimage',
            name='sight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='admin_panel.sight'),
        ),
        migrations.AddIndex(
            model_name='otpsession',
            index=models.Index(fields=['mobile'], name='admin_panel_mobile_1a0eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='otpsession',
            index=models.Index(fields=['session_id'], name='admin_panel_session_d97d40_idx'),
        ),
    ]
