# Generated by Django 5.2.3 on 2025-06-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_user_district'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_email_when_not_null',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
