# Generated by Django 5.2.3 on 2025-06-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admincommission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Admin Commission', 'verbose_name_plural': 'Admin Commissions'},
        ),
        migrations.AddField(
            model_name='admincommission',
            name='first_time_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='First-time user discount amount (10% for orders > ₹20,000, capped at ₹1,000)', max_digits=10),
        ),
        migrations.AddField(
            model_name='admincommission',
            name='referral_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Referral reward amount for the booking', max_digits=10),
        ),
    ]
