# Generated by Django 5.2.3 on 2025-06-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_alter_admincommission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
