# Generated by Django 5.2.3 on 2025-07-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
