# Generated by Django 5.2.3 on 2025-07-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_user_state'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='otpsession',
            name='admin_panel_mobile_1a0eb8_idx',
        ),
        migrations.RemoveIndex(
            model_name='otpsession',
            name='admin_panel_session_d97d40_idx',
        ),
        migrations.AddField(
            model_name='otpsession',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('vendor', 'Vendor'), ('user', 'User')], default='user', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_role_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='otpsession',
            unique_together={('mobile', 'role')},
        ),
    ]
