# Generated by Django 5.2.3 on 2025-07-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_remove_otpsession_admin_panel_mobile_1a0eb8_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='otpsession',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile_role_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='otpsession',
            index=models.Index(fields=['mobile'], name='admin_panel_mobile_1a0eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='otpsession',
            index=models.Index(fields=['session_id'], name='admin_panel_session_d97d40_idx'),
        ),
        migrations.RemoveField(
            model_name='otpsession',
            name='role',
        ),
    ]
