# Generated by Django 5.2.3 on 2025-06-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='base_price_km',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='KM included per day in base price', max_digits=10),
        ),
    ]
