# Generated by Django 5.2.3 on 2025-07-10 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='signupotp',
            name='expires_at',
        ),
    ]
