# Generated by Django 5.2.4 on 2025-07-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupotp',
            name='test',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
