# Generated by Django 5.2.4 on 2025-07-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_signupotp_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupotp',
            name='test',
        ),
        migrations.AlterField(
            model_name='signupotp',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('vendor', 'Vendor'), ('user', 'User')], default='vendor', max_length=30),
        ),
    ]
