# Generated by Django 5.2.3 on 2025-06-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_bus_base_price_km'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='vehicle_rc_number',
        ),
    ]
