# Generated by Django 5.2.3 on 2025-06-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_remove_bus_vehicle_rc_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100)),
                ('otp_code', models.CharField(max_length=6)),
                ('signup_data', models.JSONField()),
                ('otp_type', models.CharField(choices=[('mobile', 'Mobile'), ('email', 'Email')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'signup_otp',
            },
        ),
    ]
