# Generated by Django 5.2.3 on 2025-07-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_remove_signupotp_test_alter_signupotp_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagesubcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='packagesubcategory',
            unique_together={('category', 'name')},
        ),
    ]
