# Generated by Django 5.2.4 on 2025-07-16 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
        ('vendors', '0004_alter_packagesubcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorwallet',
            name='vendor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet', to='admin_panel.vendor'),
        ),
    ]
