# Generated by Django 5.2.3 on 2025-07-04 10:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_user_fcm_token'),
        ('vendors', '0005_payoutrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payoutrequest',
            name='bank_details',
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='bank_detail',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to='vendors.vendorbankdetail'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VendorWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='admin_panel.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Wallet',
                'verbose_name_plural': 'Vendor Wallets',
            },
        ),
        migrations.CreateModel(
            name='VendorWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('trip_completion', 'Trip Completion'), ('payout_processed', 'Payout Processed'), ('refund', 'Refund'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('transaction_mode', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='vendors.vendorwallet')),
            ],
            options={
                'verbose_name': 'Vendor Wallet Transaction',
                'verbose_name_plural': 'Vendor Wallet Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
