# Generated by Django 5.2.3 on 2025-07-17 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
        ('vendors', '0005_alter_vendorwallet_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorwallet',
            name='vendor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='admin_panel.vendor'),
        ),
    ]
