# Generated by Django 5.2.3 on 2025-07-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_remove_payoutrequest_bank_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorwallettransaction',
            name='transaction_mode',
        ),
        migrations.AlterField(
            model_name='vendorwallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], max_length=20),
        ),
    ]
