# Generated by Django 5.2.3 on 2025-07-29 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
        ('vendors', '0006_alter_vendorwallet_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_bus', to='admin_panel.vendor'),
        ),
        migrations.AlterField(
            model_name='package',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_package', to='admin_panel.vendor'),
        ),
    ]
