# Generated by Django 5.2.3 on 2025-07-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_remove_vendorwallettransaction_transaction_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='base_price_km',
            field=models.DecimalField(blank=True, decimal_places=2, default=100.0, help_text='KM included per day in base price', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='contract_carriage_permit',
            field=models.FileField(blank=True, null=True, upload_to='permits/'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='license',
            field=models.FileField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='rc_certificate',
            field=models.FileField(blank=True, null=True, upload_to='rc_certificates/'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('booked', 'Booked'), ('maintenance', 'Under Maintenance')], default='available', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='vehicle_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='vehicle_insurance',
            field=models.FileField(blank=True, null=True, upload_to='insurance/'),
        ),
    ]
