# Generated by Django 5.2.3 on 2025-07-09 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_otp_expires_at_signupotp_expires_at_signupotp_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='signupotp',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='signupotp',
            name='role',
        ),
    ]
