# Generated by Django 5.2.3 on 2025-06-16 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbussearchstop',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userbussearchstop',
            name='user_search',
        ),
        migrations.RemoveField(
            model_name='busbooking',
            name='total_distance',
        ),
        migrations.DeleteModel(
            name='BusBookingStop',
        ),
        migrations.DeleteModel(
            name='UserBusSearchStop',
        ),
    ]
