# Generated by Django 5.2.3 on 2025-07-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busbooking',
            name='total_travelers',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='packagebooking',
            name='total_travelers',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
