# Generated by Django 5.2.3 on 2025-06-16 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_userbussearchstop_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busbooking',
            name='total_distance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total distance including stops', max_digits=10),
        ),
        migrations.CreateModel(
            name='BusBookingStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.PositiveIntegerField(help_text='Order of the stop in the journey')),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('distance_from_previous', models.DecimalField(decimal_places=2, default=0.0, help_text='Distance from previous point in km', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='bookings.busbooking')),
            ],
            options={
                'ordering': ['stop_order'],
                'unique_together': {('booking', 'stop_order')},
            },
        ),
        migrations.CreateModel(
            name='UserBusSearchStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.PositiveIntegerField(help_text='Order of the stop in the journey')),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_stops', to='bookings.userbussearch')),
            ],
            options={
                'ordering': ['stop_order'],
                'unique_together': {('user_search', 'stop_order')},
            },
        ),
    ]
