# Generated by Django 5.2.3 on 2025-07-17 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
        ('bookings', '0002_alter_busbooking_bus_alter_busbooking_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payouthistory',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.vendor'),
        ),
    ]
