# Generated by Django 5.2.3 on 2025-06-20 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_busbooking_total_distance_busbookingstop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busbooking',
            name='one_way',
        ),
    ]
