# Generated by Django 5.2.3 on 2025-06-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_busbooking_paid_amount_packagebooking_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbussearch',
            name='one_way',
        ),
    ]
