# Generated by Django 5.2.3 on 2025-06-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_busbooking_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busbooking',
            name='children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='busbooking',
            name='female',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='busbooking',
            name='male',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='packagebooking',
            name='children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='packagebooking',
            name='female',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='packagebooking',
            name='male',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
